name: Deploy Helm Chart

on:
  push:
    branches:
      - master

jobs:
  helm-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config

    - name: Install Helm
      uses: azure/setup-helm@v3
# bitte euren namespace eintragen anstelle von default , z.B. euren namen
# muss eindeutig sein 
    - name: Deploy with Helm
      run: |

        helm upgrade --install my-release ./chart/my-app --namespace mats --create-namespace
