name: Ein Job mit dynamischer Variable je nach Zeitplan

on:
  schedule:
    - cron: '*/10 * * * *'   # Montag 08:00 UTC
    - cron: '*/5 * * * *'  # Freitag 20:00 UTC

jobs:
  dynamic-message:
    runs-on: ubuntu-latest
    steps:
      - name: Setze MESSAGE je nach Zeitplan
        id: set-message
        run: |
          case "${{ github.event.schedule }}" in
            '*/10 * * * *')
              echo "message=Was geht aabbbb?" >> $GITHUB_OUTPUT
              ;;
            '*/5 * * * *')
              echo "message=Wasssss geeeeehhhhhtttttt aaaaaabbbb" >> $GITHUB_OUTPUT
              ;;
            *)
              echo "message=Unbekannter Zeitplan" >> $GITHUB_OUTPUT
              ;;
          esac

      - name: Ausgabe der Nachricht
        run: echo "${{ steps.set-message.outputs.message }}"
